site_name: SSE Documentation Example
nav: 
    - Home: 'index.md'
    - 'User Guide':
        - 'Installation': 'compilation-and-installation.md'
        - 'Getting started': 'how-to.md'
repo_url: https://github.com/jonahaag/sse-mkdocs-exercise
site_author: Jonathan Haag